export const STAGES = {
  tutorial: {
    title: 'チュートリアル',
    badge: '練習',
    description: '操作ガイドを見ながら電車を走らせよう',
    isTutorial: true,
    targetTime: 6,
    width: 7,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 6, y: 3 },
    relayGroups: [
      {
        cells: [
          { x: 3, y: 2, part: 'entrance-right' },
          { x: 4, y: 2, part: 'entrance' },
        ],
      },
    ],
    availableRails: ['slow'],
  },
  estimateTutorial: {
    title: '見積もりチュートリアル',
    badge: '見積練習',
    description: 'メモと予想時間を入力して答え合わせしよう',
    isTutorial: true,
    isEstimateTutorial: true,
    targetTime: 6,
    width: 7,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 6, y: 3 },
    relayGroups: [
      {
        cells: [
          { x: 3, y: 2, part: 'entrance-right' },
          { x: 4, y: 2, part: 'entrance' },
        ],
      },
    ],
    availableRails: ['slow'],
  },
  1: {
    title: 'ステージ1',
    description: 'まずはレールを置く操作を覚えよう',
    targetTime: 7,
    width: 8,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 7, y: 3 },
    relayGroups: [],
    availableRails: ['slow'],
  },
  2: {
    title: 'ステージ2',
    description: '速さの違うレールを使ってみよう',
    isFastRailTutorial: true,
    targetTime: 5,
    width: 8,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 7, y: 2 },
    relayGroups: [],
    availableRails: ['slow', 'fast'],
    maxFastRails: 6,
    minimumRequiredFastRails: 2,
    enableFastRailSaving: true,
  },
  3: {
    title: 'ステージ3',
    description: '直進と高速レールを使う遠回りを比べよう',
    targetTime: 6,
    width: 8,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 7, y: 2 },
    relayGroups: [
      {
        cells: [
          { x: 4, y: 2 },
        ],
      },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 4,
  },
  4: {
    title: 'ステージ4',
    description: '障害物を避け、近道になる経路を比較しよう',
    targetTime: 5,
    width: 8,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 7, y: 2 },
    relayGroups: [],
    obstacles: [
      { x: 3, y: 2, type: 'rock' },
      { x: 2, y: 3, type: 'tree' },
      { x: 3, y: 3, type: 'tree' },
      { x: 4, y: 3, type: 'tree' },
      { x: 5, y: 3, type: 'tree' },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 8,
    minimumRequiredFastRails: 6,
    enableFastRailSaving: true,
  },
  5: {
    title: 'ステージ5',
    description: '岩と木を避け、低速で中継地点へ向かおう',
    targetTime: 8,
    width: 9,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 8, y: 2 },
    relayGroups: [
      {
        cells: [
          { x: 4, y: 2, part: 'entrance-right' },
          { x: 5, y: 2, part: 'entrance' },
        ],
      },
    ],
    obstacles: [
      { x: 2, y: 2, type: 'rock' },
      { x: 2, y: 3, type: 'tree' },
    ],
    availableRails: ['slow', 'fast'],
    relayRequiresSlowApproach: true,
  },
  6: {
    title: 'ステージ6',
    description: '目標時間を守りながら高速レールを節約しよう',
    targetTime: 7,
    width: 10,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 9, y: 2 },
    relayGroups: [
      {
        cells: [
          { x: 4, y: 2, part: 'entrance-right' },
          { x: 5, y: 2, part: 'entrance' },
        ],
      },
    ],
    obstacles: [],
    availableRails: ['slow', 'fast'],
    maxFastRails: 6,
    minimumRequiredFastRails: 2,
    relayRequiresSlowApproach: true,
    enableFastRailSaving: true,
  },
  7: {
    title: 'ステージ7',
    description: '同じ条件を満たす複数の経路を見つけよう',
    targetTime: 8.5,
    width: 10,
    height: 8,
    start: { x: 0, y: 2 },
    goal: { x: 9, y: 2 },
    relayGroups: [
      {
        cells: [
          { x: 4, y: 2, part: 'entrance-right' },
          { x: 5, y: 2, part: 'entrance' },
        ],
      },
    ],
    obstacles: [{ x: 7, y: 2, type: 'rock' }],
    availableRails: ['slow', 'fast'],
    maxFastRails: 3,
    minimumRequiredFastRails: 3,
    relayRequiresSlowApproach: true,
  },
  8: {
    title: 'ステージ8',
    description: '2つの中継地点をすべて通過しよう',
    targetTime: 10,
    width: 10,
    height: 8,
    start: { x: 0, y: 3 },
    goal: { x: 9, y: 3 },
    relayGroups: [
      {
        cells: [
          { x: 3, y: 2, part: 'entrance-right' },
          { x: 4, y: 2, part: 'entrance' },
        ],
      },
      {
        cells: [
          { x: 6, y: 4, part: 'entrance-right' },
          { x: 7, y: 4, part: 'entrance' },
        ],
      },
    ],
    obstacles: [],
    availableRails: ['slow', 'fast'],
    maxFastRails: 4,
    relayRequiresSlowApproach: true,
  },
  9: {
    title: 'ステージ9',
    description: '最短経路を外れ、8秒になる遠回りを作ろう',
    targetTime: 8,
    width: 8,
    height: 8,
    start: { x: 0, y: 3 },
    goal: { x: 7, y: 3 },
    relayGroups: [],
    obstacles: [],
    availableRails: ['slow'],
    requiresDetour: true,
  },
  10: {
    title: 'ステージ10',
    description: '高さの違うゴールと、ゴール前の「のんびり」に挑戦',
    targetTime: 7.5,
    width: 9,
    height: 8,
    start: { x: 0, y: 1 },
    goal: { x: 8, y: 6 },
    relayGroups: [],
    obstacles: [],
    availableRails: ['slow', 'fast'],
    maxFastRails: 10,
    minimumRequiredFastRails: 9,
    slowZoneRadius: 3,
    enableFastRailSaving: true,
  },
  11: {
    title: 'ステージ11',
    description: '横中継を抜けて折り返し、縦中継から別の高さへ進もう',
    isTurnaroundTutorial: true,
    targetTime: 15.5,
    width: 11,
    height: 8,
    start: { x: 0, y: 1 },
    goal: { x: 1, y: 6 },
    relayGroups: [
      {
        cells: [
          { x: 3, y: 1 },
          { x: 4, y: 1 },
        ],
      },
      {
        orientation: 'vertical',
        cells: [
          { x: 8, y: 3 },
          { x: 8, y: 4 },
        ],
      },
    ],
    turnaroundPoints: [{ x: 9, y: 1 }],
    obstacles: [
      { x: 6, y: 2, type: 'tree' },
      { x: 7, y: 2, type: 'rock' },
      { x: 9, y: 2, type: 'tree' },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 8,
    relayRequiresSlowApproach: true,
  },
  12: {
    title: 'ステージ12',
    description: '複数中継・高低差・ゴール前の「のんびり」をまとめて攻略しよう',
    targetTime: 12,
    width: 11,
    height: 8,
    start: { x: 0, y: 6 },
    goal: { x: 10, y: 1 },
    relayGroups: [
      {
        cells: [
          { x: 3, y: 5, part: 'entrance-right' },
          { x: 4, y: 5, part: 'entrance' },
        ],
      },
      {
        cells: [
          { x: 6, y: 2, part: 'entrance-right' },
          { x: 7, y: 2, part: 'entrance' },
        ],
      },
    ],
    obstacles: [
      { x: 4, y: 3, type: 'tree' },
      { x: 8, y: 4, type: 'rock' },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 4,
    minimumRequiredFastRails: 4,
    relayRequiresSlowApproach: true,
    slowZoneRadius: 3,
  },
  13: {
    title: 'ステージ13',
    description: '塞がれた道を避け、縦トンネルを上下に通過しよう',
    targetTime: 13,
    width: 10,
    height: 8,
    start: { x: 0, y: 4 },
    goal: { x: 9, y: 4 },
    relayGroups: [
      {
        orientation: 'vertical',
        cells: [
          { x: 5, y: 2 },
          { x: 5, y: 3 },
          { x: 5, y: 4 },
        ],
      },
    ],
    obstacles: [
      { x: 2, y: 4, type: 'rock' },
      { x: 3, y: 4, type: 'rock' },
      { x: 4, y: 4, type: 'tree' },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 6,
    relayRequiresSlowApproach: true,
  },
  14: {
    title: 'ステージ14',
    description: '混雑区画を迂回するか、高速で抜けるか選ぼう',
    targetTime: 10,
    width: 11,
    height: 8,
    start: { x: 0, y: 3 },
    goal: { x: 10, y: 3 },
    relayGroups: [
      {
        cells: [
          { x: 4, y: 3 },
          { x: 5, y: 3 },
        ],
      },
    ],
    obstacles: [],
    congestionZones: [
      { x: 6, y: 2 },
      { x: 7, y: 2 },
      { x: 8, y: 2 },
      { x: 6, y: 3 },
      { x: 7, y: 3 },
      { x: 8, y: 3 },
      { x: 6, y: 4 },
      { x: 7, y: 4 },
      { x: 8, y: 4 },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 9,
    relayRequiresSlowApproach: true,
  },
  15: {
    title: 'ステージ15',
    description: '縦トンネルと混雑区画をまとめて攻略しよう',
    targetTime: 13,
    width: 11,
    height: 8,
    start: { x: 0, y: 6 },
    goal: { x: 10, y: 1 },
    relayGroups: [
      {
        orientation: 'vertical',
        cells: [
          { x: 6, y: 2 },
          { x: 6, y: 3 },
          { x: 6, y: 4 },
        ],
      },
    ],
    obstacles: [],
    congestionZones: [
      { x: 2, y: 5 },
      { x: 3, y: 5 },
      { x: 4, y: 5 },
      { x: 2, y: 6 },
      { x: 3, y: 6 },
      { x: 4, y: 6 },
      { x: 2, y: 7 },
      { x: 3, y: 7 },
      { x: 4, y: 7 },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 5,
    minimumRequiredFastRails: 5,
    relayRequiresSlowApproach: true,
  },
  16: {
    title: 'ステージ16',
    description: '2つの混雑エリアを抜け、折り返してゴールへ向かおう',
    targetTime: 18,
    width: 10,
    height: 8,
    start: { x: 0, y: 1 },
    goal: { x: 1, y: 6 },
    relayGroups: [],
    turnaroundPoints: [{ x: 9, y: 1 }],
    obstacles: [],
    congestionZones: [
      { x: 2, y: 0 },
      { x: 3, y: 0 },
      { x: 4, y: 0 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
      { x: 4, y: 5 },
      { x: 5, y: 5 },
      { x: 6, y: 5 },
      { x: 4, y: 6 },
      { x: 5, y: 6 },
      { x: 6, y: 6 },
      { x: 4, y: 7 },
      { x: 5, y: 7 },
      { x: 6, y: 7 },
    ],
    availableRails: ['slow', 'fast'],
    maxFastRails: 8,
  },
}
